// import type { Metadata } from "next";
// import { Noto_Serif_JP,Noto_Sans,Zen_Old_Mincho} from "next/font/google";
// import "./globals.css";

// const notoSerifJp = Noto_Serif_JP({
//   weight:["500","700"],
//   variable: "--font-noto-serif-jp",
//   subsets: [],
// });
// const notoSans = Noto_Sans({
//   weight:["500"],
//   variable: "--font-noto-sans",
//   subsets: [],
// });

// const zenOldMincho = Zen_Old_Mincho({
//   weight:["600","700"],
//   variable: "--font-zen-old-mincho",
//   subsets: [],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="ja">
//       <body
//         className={`${notoSerifJp.variable} ${notoSans.variable} ${zenOldMincho.variable}  antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// src/app/layout.tsx
import "./globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="antialiased"> 
        {children}
      </body>
    </html>
  );
}