import type { Metadata } from "next";
import { Noto_Serif_JP,Zen_Old_Mincho} from "next/font/google";
import "./globals.css";

const notoSerifJp = Noto_Serif_JP({
  weight:["500","700"],
  variable: "--font-noto-serif-jp",
  subsets: [],
});

const zenOldMincho = Zen_Old_Mincho({
  weight:["500","700"],
  variable: "--font-zen-old-mincho",
  subsets: [],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSerifJp.variable} ${zenOldMincho.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
